### ISSUE TITLE
Error : unkown

### ISSUE THREAD

**Issue by HyzCo** [kronoscloud/Instagram-Account-Creator#1]
Hi,
I am developing the your project. But ım getting an error:
Error screen shot: http://prntscr.com/dzq6js
Help

**Comment by sykope** [comment]
hello
can you tell how did you execute the programme I am not realy dat good at C# pls
help

**Comment by HyzCo** [comment]
Hello,
The program is working incorrectly.

**Comment by sykope** [comment]
but how to launch it like on your screem

**Comment by HyzCo** [comment]
Hello,
This is not the main program, but ım developed program. But I'm getting an error.
Error: Unkown

**Comment by ewwink** [comment]
the signature is blocked, need to generate new sig.

**Comment by HyzCo** [comment]
I do not know how to use. Help please

**Comment by HyzCo** [comment]
You edit and update the source code

**Comment by kronoscloud** [comment]
This hasn't been updated in over 2 years.

I am going to be making a new version of this in the next month or so.
