### ISSUE TITLE
tracable data?

### ISSUE THREAD

**Issue by zeradi** [kronoscloud/Instagram-Account-Creator#2]
I'm not that good at coding/reading it, but i think i read somewhere about android in there.
does the program change it every time? does is leave traces so the created accounts are getting banned?

**Comment by zeradi** [comment]
and i get error: unknown when i try to register an account

**Comment by HyzCo** [comment]
Zeradi me too ı get error : unkown when i try to register an account

**Comment by HyzCo** [comment]
and ı get error screenshot : http://prnt.sc/dzq6js

**Comment by kronoscloud** [comment]
This hasn't been updated in over 2 years.

I am going to be making a new version of this in the next month or so.
